version: '3'
services:
  llrp:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.inventory
    image: llrp_inventory
    container_name: llrp_inventory
    environment:
      - ANT_ADDR=10.10.31.170
      - INTERVAL=2
      - MQTT_BROKER=10.10.10.83
      - MQTT_TOPIC=llrp/1
      - TX_POWER=81 #max
      - MODE=1003
        #restart: always
    network_mode: host

